export const GET_PHOTOS_REQUESTED = "GET_PHOTOS_REQUESTED";
export const GET_PHOTOS_REJECTED = "GET_PHOTOS_REJECTED";
export const GET_PHOTOS_FULLFILLED = "GET_PHOTOS_FULLFILLED";
export const PHOTO_ADDED = "PHOTO_ADDED";

export const USER_NAME_SET = "USER_NAME_SET";
export const GET_MESSAGES_FULLFILLED = "GET_MESSAGES_FULLFILLED";
export const MESSAGE_ADDED = "MESSAGE_ADDED";
export const POST_MESSAGE = "POST_MESSAGE";
