export const GET_PHOTOS_REQUESTED = 'GET_PHOTOS_REQUESTED';
export const GET_PHOTOS_REJECTED = 'GET_PHOTOS_REJECTED';
export const GET_PHOTOS_FULLFILLED = 'GET_PHOTOS_FULLFILLED';
export const PHOTO_ADDED = 'PHOTO_ADDED';

